version: "3.8"

services:
  consumer:
    build:
      context: ./ConsumerService
    ports:
      - "4567:4567"
    environment:
      DB_HOST: db
      DB_NAME: clew_medical
      DB_USER: admin
      DB_PASSWORD: password
      RABBIT_HOST: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASS: password
#    volumes:
#      - #todo
    depends_on:
      - postgresdb
      - rabbitmq

  publisher:
    build:
      context: ./PublisherService
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASS: password
#    volumes:
#      - #todo
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.1-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

  postgresdb:
    image: postgres:12.0
    container_name: postgresdb
    environment:
      PGDATA: var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
